# Generated by Django 4.2.6 on 2023-12-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanchal', '0002_remove_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
